title: Faith Olajide | Cybersecurity Portfolio
description: Cybersecurity projects, final papers, and technical work.
baseurl: ""
url: "[https://justfaith98.github.io](https://justfaith98.github.io)"

remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

show_downloads: true
