title: Faith Olajide | Cybersecurity Portfolio
description: Cybersecurity projects, final papers, and technical work.
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

show_downloads: true
