title: Faith Olajide's Portfolio # Replace with your name
subtitle: A Portfolio Jekyll Theme Built for Developers
description: Cybersecurity Professional | Cybersecurity Student Passionate About Social Engineering and Human-Focused Security. Exploring the Psychology Behind Secure Systems.
show_downloads: false
google_analytics:

# Navigation links
nav_links:
  - name: Home
    url: /
  - name: Resume
    url: /resume.html
  - name: Labs
    url: /labs.html
  - name: Senior Design Project
    url: /senior-design.html

# Social links
github_username: justfaith98
linkedin_username: faith-olajide-58075514b
email: your-email@example.com

# Edit Author details
author_logo: profile.png # You may need to add an image named profile.png to your assets folder
author: Faith Olajide
author_bio: Hi, my name is Faith Olajide. I'm a Cybersecurity Professional & Student Exploring the Psychology Behind Secure Systems.
author_email: "your-email@example.com"
author_location: # Add your location here if desired
author_website_url: "https://justfaith98.github.io"
typewrite-text: Faith Olajide's Portfolio
hero_cover_img: sample_cover.jpg # You may need to add an image named sample_cover.jpg to your assets folder

# Experiences (Example data - replace with your own)
author_work_experiences:
  - company_name: Google
    company_logo: google.png
    company_url: https://google.com
    designation: Software Engineer
    description: Worked on various Google Products
    visibility: true

# Education (Example data - replace with your own)
author_education_details:
  - college_logo: mit.png
    college_name: MIT
    college_url: https://mit.org
    college_degree: CS Engineer
    description: Bachelor of Technology
    visibility: true

# Projects (Example data - replace with your own)
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: https://gamershub.in
    visibility: true

# Social links (optional)
# You can uncomment and add your usernames for any of these platforms
# twitter_username:
# instagram_username:
# facebook_username:
# behance_username:
# medium_username:
# telegram_username:
# dribbble_username:
# flickr_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
