title: Faith Olajide's Portfolio # Replace with your name
description: Cybersecurity Professional | Cybersecurity Student Passionate About Social Engineering and Human-Focused Security. Exploring the Psychology Behind Secure Systems. # Replace with your professional title/description
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

# Navigation links (optional)
nav_links:
  - name: Home
    url: /
  - name: Resume
    url: /resume.html
  - name: Labs
    url: /labs.html
  - name: Senior Design Project
    url: /senior-design.html

# Social links (optional)
github_username: justfaith98 # Replace with your GitHub username
linkedin_username: faith-olajide-58075514b # Replace with your LinkedIn username
email: your-email@example.com # Replace with your email
